// {{PLATFORM_NAME}} Source Plugin for GrayJay
// Generated by @grayjay/source-generator

{{IMPORTS}}

interface Config {
  name: string;
  platformUrl: string;
  version: number;
}

let config: Config;

const BASE_URL = '{{BASE_URL}}';
const PLATFORM = '{{PLATFORM_NAME}}';

// Plugin state
const state = {
  {{STATE_PROPERTIES}}
};

// Source Methods
source.enable = function (conf: any) {
  config = conf;
  {{LOAD_STATE}}
  log('Plugin enabled: ' + config.name);
};

source.getHome = function (): VideoPager {
  log('getHome called');
  throw new ScriptException('Not implemented yet');
};

{{SEARCH_METHODS}}

source.isChannelUrl = function (url: string): boolean {
  const urlLower = url.toLowerCase();
  return urlLower.includes('{{PLATFORM_HOSTNAME}}') && 
         (urlLower.includes('channel') || urlLower.includes('user') || urlLower.includes('@'));
};

source.getChannel = function (url: string): PlatformChannel {
  log('getChannel called with url: ' + url);
  throw new ScriptException('Not implemented yet');
};

source.getChannelContents = function (url: string): VideoPager {
  log('getChannelContents called');
  throw new ScriptException('Not implemented yet');
};

source.isContentDetailsUrl = function (url: string): boolean {
  return url.includes('{{PLATFORM_HOSTNAME}}');
};

source.getContentDetails = function (url: string): PlatformVideoDetails {
  log('getContentDetails called with url: ' + url);
  throw new ScriptException('Not implemented yet');
};

{{PLAYLIST_METHODS}}

{{COMMENT_METHODS}}

source.saveState = function (): string {
  return JSON.stringify(state);
};

// Helper Functions
function log(message: string) {
  console.log('[{{PLATFORM_NAME}}] ' + message);
}

log('{{PLATFORM_NAME}} script loaded');
